apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: med-erp
  annotations:
    kubernetes.io/description: "Application secrets — replace before deploying"
type: Opaque
data:
  MONGODB_URI_USER: bW9uZ29kYitzcnY6Ly9heXVzaGthbWJsZTgyMF9kYl91c2VyOkF5dXNoOTI4NEBjbHVzdGVyMC41bDh4ZjRiLm1vbmdvZGIubmV0L3VzZXJfZGI/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5

  MONGODB_URI_PRODUCT: bW9uZ29kYitzcnY6Ly9heXVzaGthbWJsZTgyMF9kYl91c2VyOkF5dXNoOTI4NEBjbHVzdGVyMC41bDh4ZjRiLm1vbmdvZGIubmV0L3Byb2R1Y3RzX2RiP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eQ==

  MONGODB_URI_ORDER: bW9uZ29kYitzcnY6Ly9heXVzaGthbWJsZTgyMF9kYl91c2VyOkF5dXNoOTI4NEBjbHVzdGVyMC41bDh4ZjRiLm1vbmdvZGIubmV0L29yZGVyX2RiP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eQ==

  JWT_SECRET: NDA0RTYzNTI2NjU1NkE1ODZFMzI3MjM1NzUzODc4MkY0MTNGNDQyODQ3MkI0QjYyNTA2NDUzNjc1NjZCNTk3MA==